cleanerapp/urls.py
# myapp/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('cleaner_works/', views.cleaner_works, name='cleaner_works'),
    path('staff_works/', views.staff_works, name='staff_works'),
    path('setting_works/', views.setting_works, name='setting_works'),
    path('update_status/<int:work_id>/<str:status>/', views.update_status, name='update_status'),
    path('reset_status/<int:work_id>/<str:status>/', views.reset_status, name='reset_status'),
    path('edit_work/<int:work_id>/', views.edit_work, name='edit_work'),
    path('delete_work/<int:work_id>/', views.delete_work, name='delete_work'),
    path('add_work/', views.add_work, name='add_work'),
    path('workdata-history/', views.get_workdata_history, name='workdata_history'),
    path('submit_verification/<int:work_id>/', views.submit_verification, name='submit_verification'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.register_view, name='register'),

    # Add other URL patterns as needed
]

cleaningsystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('cleanerapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cleanerapp/models.py
from typing import Any
from django.contrib.auth.models import User
from django.db import models
class Cleaner(models.Model):
    # Define choices for sex
    SEX_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    sex = models.CharField(max_length=10, choices=SEX_CHOICES)

    def __str__(self):
        return self.user.first_name
    
    class Meta:
        verbose_name_plural = "พนักงานทำความสะอาด"


class Building(models.Model):
    name = models.CharField(max_length=100, unique=True)
    total_floors = models.PositiveIntegerField()

    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "ตึก"

class Room(models.Model):
    room_name = models.CharField(max_length=100)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    floor_num = models.PositiveIntegerField()

    def __str__(self):
        return f" {self.building.name} ห้อง {self.room_name} ชั้น {self.floor_num}"

    class Meta:
        unique_together = ('room_name', 'building', 'floor_num')
        verbose_name_plural = "ห้อง"

class Work(models.Model):
    work_name = models.CharField(max_length=100)
    cleaner = models.ForeignKey(Cleaner, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    WEEKDAYS = [
        ('Sunday', 'Sunday'),
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednesday', 'Wednesday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
    ]
   # Use CharField with choices argument
    day = models.CharField(max_length=9, choices=WEEKDAYS)  # Set max_length to accommodate the longest weekday name
    def __str__(self):
        return f"Please {self.cleaner.user.first_name} {self.work_name} in {self.room} on {self.day}"

    class Meta:
        unique_together = ('work_name', 'cleaner', 'room', 'day')
        verbose_name_plural = "งาน"

class Checker(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name_plural = "พนักงานเช็คความสะอาด"

class WorksData(models.Model):
    date = models.DateField()
    status = models.CharField(max_length=20)
    rating = models.IntegerField(default=0)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500)
    staff = models.CharField(max_length=100)
    
    def __str__(self):
        return f"WorksData for Work {self.work_id}, Status: {self.status}"

    class Meta:
        verbose_name_plural = "บันทึกข้อมูลทำความสะอาด"


    

class Staff(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
       return self.user.first_name
    
    class Meta:
        verbose_name_plural = "แอดมิน"

templates/add_work.html
{% include 'navbar.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Work</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/add.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
</head>

    <body class="background" style="font-family: 'Kanit-Medium', sans-serif;">
    <h3 class="text-center mt-4" style="color: #14213D; font-weight: bold;">Add Work</h3>
    <div class="container mt-5 text-center mb-5">
        <div class="container bg d-flex flex-column justify-content-center align-items-center">
            <div class="images">
            <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 198 194" fill="none">
                <path d="M197.485 96.7733C197.485 150.22 153.277 193.547 98.7427 193.547C44.2086 193.547 0 150.22 0 96.7733C0 43.3269 44.2086 0 98.7427 0C153.277 0 197.485 43.3269 197.485 96.7733Z" fill="#D9D9D9"/>
            
                <!-- Include the image and center it -->
                <image x="24" y="22" width="150" height="150" xlink:href="{% static 'images/ftu_logo-removebg-preview.png' %}" />
            </svg>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group row m-3">
                <label for="work_name" class="col-sm-5 col-form-label">Work Name:</label>
                <div class="col-sm-7">
                    <input type="text" class="form-control bor" id="work_name" name="work_name" required>
                </div>
            </div>

            <div class="form-group row m-3">
                <label for="work_room" class="col-sm-5 col-form-label">Select Room:</label>
                <div class="col-sm-7">
                    <select class="form-control bor" id="work_room" name="work_room">
                        {% for room in rooms %}
                            <option value="{{ room.id }}">{{ room.building }} ชั้น {{ room.floor_num }} ห้อง {{ room.room_name }} </option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group row m-3">
                <label for="work_cleaner" class="col-sm-5 col-form-label">Cleaner:</label>
                <div class="col-sm-7">
                    <select class="form-control bor" id="work_cleaner" name="work_cleaner" required>
                        <option value="" disabled selected>Select a Cleaner</option>
                        {% for cleaner in cleaners %}
                            <option value="{{ cleaner.id }}">{{ cleaner.user.get_full_name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group row m-3">
                <label for="work_day" class="col-sm-5 col-form-label">Date:</label>
                <div class="col-sm-7">
                    <select class="form-control bor" id="work_day" name="work_day" required>
                        <option value="" disabled selected>เลือกวัน</option>
                        <option value="Sunday">Sunday</option>
                        <option value="Monday">Monday</option>
                        <option value="Tuesday">Tuesday</option>
                        <option value="Wednesday">Wednesday</option>
                        <option value="Thursday">Thursday</option>
                    </select>
                </div>
            </div>

            <!-- Add fields for other relevant information -->
            <button type="submit" class="btn btn-primary m-3">Add Work</button>
        </form>
    </div>
    </div>

    
</body>
</html>

templates/cleaner.html
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/cleaner.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>

<body style="font-family: 'Kanit-Medium', sans-serif;">

<div class="filter-bar">
    <div class="filter-dropdown">
        <select id="buildingFilter">
            <option value="">ตึกทั้งหมด</option>
            <!-- Add options dynamically from your database -->
            {% for building in building_choices %}
                <option value="{{ building.name }}">{{ building.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="filter-dropdown">
        <select id="floorFilter">
            <option value="">ชั้นทั้งหมด</option>
            <!-- Add options dynamically from your database -->
            {% for floor in floor_choices %}
                <option value="{{ floor }}">{{ floor }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="filter-dropdown">
        <select id="roomFilter">
            <option value="">พิกัดทั้งหมด</option>
            {% for room in room_choices %}
                <option value="{{ room }}">{{ room }}</option>
            {% endfor %}
        </select>
    </div>

    <button type="button" onclick="applyFilters()">ยืนยัน</button>
</div>
<!-- Your content goes here -->
<div class="container mt-5 content">
    <h3 class="text-center">งานที่คุณต้องทำสำหรับวันนี้</h3>
    <div class="row">
        {% for workitem in works_data %}
        {% with workitem.worksdata_set.first as work_data %}
        {% if work_data.status != 'เสร็จสิ้น' and work_data.status != 'ประเมินเรียบร้อย' %}
            <div class="col-md-4 mb5">
                <div class="card mb-3 text-center">
                    <div class="card-body">
                        <!-- <img src="{{ workitem.cleaner.profile_image.url }}" alt="{{ workitem.cleaner.user.username }}'s Profile" width="90" height="90"> -->
                        <h5 class="card-title{{ workitem.id }} text-center">{{ workitem.work_name }}</h5>
                        <p class="card-text{{ workitem.id }}"">สถานที่: <span >{{ workitem.room.room_name }}</span></p>
                        <p class="card-text{{ workitem.id }}">อาคาร: <span >{{ workitem.room.building.name }} ชั้น {{ workitem.room.floor_num }}</span></p>
                        <p class="card-text{{ workitem.id }}" style="display: none;">วัน<span>{{ workitem.day }}</span></p>
                        <p class="card-text{{ workitem.id }}" >ผู้ทำงาน: <span id="taskUser{{ workitem.id }}">{{ workitem.cleaner.user.get_full_name }}</span></p>
                        <p class="card-text{{ workitem.id }}">สถานะ: <span id="taskStatus{{ workitem.id }}">
                       
                                {% if work_data %}
                                    {{ work_data.status }}
                                {% else %}
                                ยังไม่อัพเดตสถานะ
                                {% endif %}
                        </span></p>
                        <div class="d-flex justify-content-center m-3 mt-4">
                                <button class="btn" id="Process{{ workitem.id }}" onclick="changeTaskStatus({{ workitem.id }}, 'กำลังทำงาน')">กำลังทำงาน</button>
                                <button class="btn" style="margin-left: 20px;" id="Done{{ workitem.id }}" onclick="changeTaskStatus({{ workitem.id }}, 'เสร็จสิ้น')">เสร็จสิ้น</button>
                            </div>

                        

                    </div>
                </div>
            </div>
            {% else %}
            {% endif %}
            {% endwith %}
        {% endfor %}
        
    </div>
</div>





<script>
    function changeTaskStatus(work_id, status) {
        // เชื่อมโยงกับ API Django เพื่ออัปเดตสถานะ
        fetch(`/update_status/${work_id}/${status}/`, {
            method: 'GET',
        })
        .then(response => response.json())
        .then(data => {
            if (data.message === 'Status updated successfully') {
                // Update the status elements in your HTML
                var statusElement = document.getElementById(`taskStatus${work_id}`);
                var InProcessButton = document.getElementById(`Process${work_id}`);
                var DoneButton = document.getElementById(`Done${work_id}`);
    
                if (status === 'กำลังทำงาน') {
                    statusElement.textContent = 'กำลังทำงาน';
                    InProcessButton.disabled = true;
                    DoneButton.disabled = false;
                } else if (status === 'เสร็จสิ้น') {
                        statusElement.textContent = 'เสร็จสิ้น';
                        InProcessButton.disabled = true;
                        DoneButton.disabled = true;
                    } else {
                        console.error('ไม่สามารถกดปุ่ม "Done" ได้ในสถานะนี้');
                    }
            
    
                // You can access the work_id from the response
                console.log(`Work ID: ${data.work_id}`);
            } else {
                console.error(`เกิดข้อผิดพลาด: ${data.message}`);
            }
        })
        .catch(error => {
            console.error('เกิดข้อผิดพลาดในการส่งคำขอ:', error);
        });
    }
    
    
    
    </script>

    <script>
        // JavaScript code to set selected options based on URL parameters
        window.addEventListener('DOMContentLoaded', function () {
            const urlParams = new URLSearchParams(window.location.search);
            const building = urlParams.get('building');
            const floor = urlParams.get('floor');
            const room = urlParams.get('room');

            if (building) {
                document.getElementById('buildingFilter').value = building;
            }
            if (floor) {
                document.getElementById('floorFilter').value = floor;
            }
            if (room) {
                document.getElementById('roomFilter').value = room;
            }
        });

        // Rest of your JavaScript code for applying filters
        function applyFilters() {
            const building = document.getElementById('buildingFilter').value;
            const floor = document.getElementById('floorFilter').value;
            const room = document.getElementById('roomFilter').value;
            let url = window.location.href.split('?')[0];
            if (building || floor || room) {
                url += `?building=${building}&floor=${floor}&room=${room}`;
            }
            window.location.href = url;
        }
    </script>



</body>
</html>

templates/delete_work.html
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Work</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/delete.css' %}">

</head>
<body style="font-family: 'Kanit-Medium', sans-serif;">
    <div class="content">
        
        <h3 class="text-center mt-4" style="font-size: 30px; color: #14213D; font-weight: bold;">Delete Work</h3>
        <div class="container bg mt-5 d-flex flex-column justify-content-center align-items-center">
            <div class="images">
            <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 198 194" fill="none">
                <path d="M197.485 96.7733C197.485 150.22 153.277 193.547 98.7427 193.547C44.2086 193.547 0 150.22 0 96.7733C0 43.3269 44.2086 0 98.7427 0C153.277 0 197.485 43.3269 197.485 96.7733Z" fill="#D9D9D9"/>
            
                <!-- Include the image and center it -->
                <image x="24" y="22" width="150" height="150" xlink:href="{% static 'images/ftu_logo-removebg-preview.png' %}" />
            </svg>
        </div>
            <p class="text-center">คุณแน่ใจว่าต้องการลบงานนี้ใช่ไหม</p>
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">ยืนยัน</button>
            </form>
        </div>
    </div>

    
</body>
</html>

templates/edit_work.html
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Work</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/edit.css' %}">
    <!-- Add any necessary CSS or Bootstrap includes here -->
</head>
<body style="font-family: 'Kanit-Medium', sans-serif;">  

    <div class="content">

            <h3 class="text-center mt-4" style="font-size: 30px; color: #14213D; font-weight: bold;">Edit Work</h3>
            <div class="container bg mt-5 d-flex flex-column justify-content-center align-items-center">
            <div class="images">
            <svg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 198 194" fill="none">
                <path d="M197.485 96.7733C197.485 150.22 153.277 193.547 98.7427 193.547C44.2086 193.547 0 150.22 0 96.7733C0 43.3269 44.2086 0 98.7427 0C153.277 0 197.485 43.3269 197.485 96.7733Z" fill="#D9D9D9"/>
            
                <!-- Include the image and center it -->
                <image x="24" y="22" width="150" height="150" xlink:href="{% static 'images/ftu_logo-removebg-preview.png' %}" />
            </svg>
        </div>
        <p class="text-center">งาน : {{ work.work_name }} </p>
        <p class="text-center">สถานที่ : {{ work.room }}</p>
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="d-flex justify-content-center align-items-center">
                        <p>
                            <label for="cleaner" style="color: white; font-size: 18px; font-weight: 500;">Select Cleaner</label>
                        </p>
                    </div>
                    <select class="form-control" id="cleaner" name="cleaner" style="border-radius: 20px;">
                        {% for cleaner in cleaners %}
                            <option value="{{ cleaner.id }}"{% if work.cleaner.id == cleaner.id %}selected{% endif %} style="text-align: center;">{{ cleaner.user.get_full_name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="d-flex justify-content-center align-items-center">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
    
</body>
</html>

templates/login.html
<!-- login.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
   
</head>
<body style="font-family: 'Kanit-Medium', sans-serif;">
    <div class="container">
    <p style="font-weight: bold; text-align: center; font-size: 19px; margin-top: -10%;">“แท้จริงความสะอาดนั้นเป็นส่วนหนึ่งของการศรัทธา<br>และการกล่าว อัลฮัมดูลิลลาฮฺนั้นเป็นสิ่งที่จะเติมเต็มตาชั่ง” <br>[รายงานโดยมุสลิม  : 223]</p>
        <div class="row" style="margin-top: -5%;">
            <div class="col-md-6 offset-md-3">
                <!-- กล่องล็อกอิน -->
                
                <div class="login-box p-4 mb-5">
                    <h2 class="login-header">เข้าสู่ระบบ</h2>
                    <hr class="mb-4">
                    <!-- เพิ่มรูปไอคอนคน -->
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <img src="{% static 'images/icon-login.png' %}" alt="" style="width: 20px; height: 20px; margin-top: -5px; margin-right: 5px;"><label for="username" class="form-label">ชื่อผู้ใช้งาน:</label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <img src="{% static 'images/icon-password.png' %}" alt="" style="width: 20px; height: 20px; margin-top: -5px; margin-right: 5px;"><label for="password" class="form-label">รหัสผ่าน:</label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        
                            {% if messages %}
                                <div class="alert alert-danger text-center">
                                    <ul class="messages">
                                        {% for message in messages %}
                                            <li style="list-style: none;">{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- เรียกใช้ Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

</body>
</html>

templates/setting.html
{% include 'navbar.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ตั้งค่างาน</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/cleaner.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha2/dist/js/bootstrap.min.js"></script>



</head>
<body class="background" style="font-family: 'Kanit-Medium', sans-serif;">
    <div class="filter-bar">
        <div class="filter-dropdown">
            
            <select id="dayFilter">
                <option value="">วัน</option>
                <!-- Add options dynamically from your database -->
                {% for day in day_choices %}
                    <option value="{{ day }}">{{ day }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="filter-dropdown">
            <select id="buildingFilter">
                <option value="">ตึกทั้งหมด</option>
                <!-- Add options dynamically from your database -->
                {% for building in building_choices %}
                    <option value="{{ building.name }}">{{ building.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="filter-dropdown">
            <select id="floorFilter">
                <option value="">ชั้นทั้งหมด</option>
                <!-- Add options dynamically from your database -->
                {% for floor in floor_choices %}
                    <option value="{{ floor }}">{{ floor }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="filter-dropdown">
            <select id="roomFilter">
                <option value="">พิกัดทั้งหมด</option>
                <!-- Add options dynamically from your database -->
                {% for room in room_choices %}
                    <option value="{{ room }}">{{ room }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="filter-dropdown">
            <select id="cleanerFilter">
                <option value="">เจ้าหน้าที่ทำความสะอาดทั้งหมด</option>
                <!-- Add options dynamically from your database -->
                {% for cleaner in cleaner_choices %}
                    <option value="{{ cleaner }}">{{ cleaner }}</option>
                {% endfor %}
            </select>
        </div>
        <!-- <button type="button" style="font-size: 20px;" onclick="resetFilters()">รีเซ็ตตัวกรอง</button> -->
        <button type="button" style="font-size: 20px;" onclick="applyFilters()">ยืนยัน</button>
    </div>
   
    <div class="container mt-5">
        <div class="d-flex justify-content-center">
            <h3>งานทั้งหมด</h3>
        </div>
        <div class="d-flex justify-content-end mb-5">
            <button class="btn" style="border-radius: 40px;"><a href="{% url 'add_work' %}" class="text-success text-decoration-none">เพิ่มงาน</a></button>
        </div>
        
        
        <div class="row">
            {% for workitem in works_data %}
            {% with workitem.worksdata_set.first as work_data %}
        
                <div class="col-md-4 mb-5">
                    <div class="card mb-3 text-center">
                        <div class="card-body">
                            <div class="d-flex justify-content-center">
                                {% if workitem.cleaner.profile_image %}
                                    <img src="{{ workitem.cleaner.profile_image.url }}" alt="{{ workitem.cleaner.user.username }}'s Profile" width="90" height="90">
                                {% else %}
                                    <img src="https://icon2.cleanpng.com/20180419/sbw/kisspng-aspria-fitness-computer-icons-user-clip-art-my-account-icon-5ad833cf5b08f0.6326680415241184793729.jpg" alt="Default Profile" width="90" height="90">
                                {% endif %}
                            </div>
                            
                            <h5 class="card-title{{ workitem.id }} text-center">{{ workitem.work_name }}</h5>
                            <p class="card-text{{ workitem.id }}">สถานที่: <span >{{ workitem.room.room_name }}</span></p>
                            <p class="card-text{{ workitem.id }}">อาคาร: <span >{{ workitem.room.building.name }} ชั้น {{ workitem.room.floor_num }}</span></p>
        
                            <p class="card-text{{ workitem.id }}">ผู้ทำงาน: <span id="taskUser{{ workitem.id }}">{{ workitem.cleaner.user.get_full_name }}</span></p>
                            <p class="card-text{{ workitem.id }}">สถานะ: <span id="taskStatus{{ workitem.id }}">
                                {% if work_data %}
                                        {{ work_data.status }}
                                    {% else %}
                                        ยังไม่อัพเดตสถานะ
                                    {% endif %}
                            </span></p>
                            <p class="card-text{{ workitem.id }}" ><span>{{ workitem.day }}</span></p>
                           
                            
                            <div class="d-flex justify-content-center m-3 mt-4">
                                <button class="btn"><a href="{% url 'edit_work' workitem.id %}" class="text-success text-decoration-none">Edit Work</a></button>
                                <button class="btn" style="margin-left: 20px;"><a href="{% url 'delete_work' workitem.id %}" class="text-success text-decoration-none">Delete Work</a></button>
                            </div>
                            
                        </div>
                    </div>
                </div>

                {% endwith %} 
            {% endfor %}
        </div>
    </div>
   
    
    

    

    <script>
        // JavaScript code to set selected options based on URL parameters
        window.addEventListener('DOMContentLoaded', function () {
            const urlParams = new URLSearchParams(window.location.search);
            const building = urlParams.get('building');
            const floor = urlParams.get('floor');
            const room = urlParams.get('room');
            const cleaner = urlParams.get('cleaner');
            const day = urlParams.get('day');

            if (building) {
                document.getElementById('buildingFilter').value = building;
            }
            if (floor) {
                document.getElementById('floorFilter').value = floor;
            }
            if (room) {
                document.getElementById('roomFilter').value = room;
            }
            if (cleaner) {
                document.getElementById('cleanerFilter').value = cleaner;
            }
            if (day) {
                document.getElementById('dayFilter').value = day;
            }
        });
    
        // Rest of your JavaScript code for applying filters
        function applyFilters() {
            const building = document.getElementById('buildingFilter').value;
            const floor = document.getElementById('floorFilter').value;
            const room = document.getElementById('roomFilter').value;
            const cleaner = document.getElementById('cleanerFilter').value;
            const day = document.getElementById('dayFilter').value;

            let url = window.location.href.split('?')[0];
            if (building || floor || room || cleaner || day) {
                url += `?building=${building}&floor=${floor}&room=${room}&cleaner=${cleaner}&day=${day}`;
            }
            window.location.href = url;
        }
        function resetFilters() {
            // Reset the day filter
            document.getElementById('dayFilter').selectedIndex = 0;

            // Reset the building filter
            document.getElementById('buildingFilter').selectedIndex = 0;

            // Reset the floor filter
            document.getElementById('floorFilter').selectedIndex = 0;

            // Reset the room filter
            document.getElementById('roomFilter').selectedIndex = 0;

            // Reset the cleaner filter
            document.getElementById('cleanerFilter').selectedIndex = 0;

            // Optionally, you can trigger the filter action
            applyFilters();
}

    </script>
  


</body>
</html>